### PR TITLE
Add AscentCore Labs section to "Our Work" page

### PR DESCRIPTION
**Pull request by SerbanCiprian**
## Why 

We want to showcase AscentCore Labs' works on our website. Our Work seems to be the place to do that.

## What 
- [x] Add the AscentCore Labs section to Our Work page as per the mockups
- [ ] The section "Recent projects" will display the Case Studies in a carousel 

## Notes

Mockups for the Our Work page: https://app.moqups.com/yUwnyd2GEz/edit/page/a5c92ac96

Screenshot 2021-04-05 at 09 37 55

### CODE REVIEW

**Comment by hcristea** [comment]
@SerbanCiprian, if I'm not mistaking, the last check item is implemented already, right?

**Comment by hcristea** [comment]
Apologies, it seems the section displays the blog posts and not the Case Studies.

**Comment by SerbanCiprian** [comment]
> @SerbanCiprian, if I'm not mistaking, the last check item is implemented already, right?

Yes. It has been partially implemented. Only the AscentCore Labs section.

**Comment by SerbanCiprian** [comment]
> Apologies, it seems the section displays the blog posts and not the Case Studies.

Yes. I will implement Case Studies but I did not know exactly who they are.

**Comment by hcristea** [comment]
@SerbanCiprian, I'll write a new issue for that

**Pull request merged**
